services:
  drupal:
    image: drupal-11-image:v1.1
    restart: unless-stopped
    ports:
      - ${DRUPAL_PORTS}
    volumes:
      - drupal_modules:/opt/drupal/web/modules
      - drupal_profiles:/opt/drupal/web/profiles
      - drupal_themes:/opt/drupal/web/themes
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - drupal_network

  mariadb:
    image: mariadb:11.8
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DRUPAL_DB_NAME}
      - MYSQL_USER=${DRUPAL_DB_USER}
      - MYSQL_PASSWORD=${DRUPAL_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DRUPAL_DB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - drupal_network

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  mariadb_data:

networks:
  drupal_network:
    driver: bridge